models:
  - name: stg_fred_metros
    description: >
      Staging model for FRED metro-level indicators. Cleans dates,
      extracts year, and maps series IDs to metro/indicator metadata.
    columns:
      - name: date
        description: Date of the FRED observation
      - name: series_id
        description: FRED series ID
      - name: year
        description: Extracted year from date
      - name: value
        description: Reported indicator value
      - name: geo_id
        description: Metro area code from FRED
      - name: city
        description: City name for the metro
      - name: indicator
        description: Indicator type (e.g., Case-Shiller, CPI, Unemployment Rate)

  - name: stg_fred_rates
    description: >
      Staging model for FRED macroeconomic rates. Cleans dates,
      extracts year, and maps series IDs to indicator metadata.
    columns:
      - name: date
        description: Date of the FRED observation
      - name: year
        description: Extracted year from date
      - name: series_id
        description: FRED series ID
      - name: value
        description: Reported rate value
      - name: rate_name
        description: Name of the macroeconomic rate (e.g., Fed Funds, Mortgage 30y)