models:
  - name: demographics_by_metro
    description: Aggregates demographic metrics by metro area
    columns:
      - name: year
        tests: [not_null]
      - name: metro_code
        tests: [not_null]
      - name: city
        tests: [not_null]
      - name: total_population
        tests:
          - not_null
          - relationships:
              to: ref('stg_census')
              field: metro_code
      - name: median_household_income
        tests: [not_null]

  - name: population_growth_rate
    description: Computes year-over-year population growth rates for each metro
    columns:
      - name: year
        tests: [not_null]
      - name: metro_code
        tests: [not_null]
      - name: city
        tests: [not_null]
      - name: total_population
        tests: [not_null]
      - name: population_growth_rate
        tests:
          - not_null